VIDEO_DIR = '/storage/wmscontent/eventialsVOD/mp4/'
THUMB_DIR = '/storage/thumbs/'
AWS_BUCKET_NAME = ''
AWS_ACCESS_KEY = ''
AWS_SECRET_KEY = ''
AWS_MEDIA_PATH = 'media/'
AWS_THUMB_PATH = 'streaming-thumbs/'
